//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCSEntities : DbContext
    {
        public DCSEntities()
            : base("name=DCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<StudentClassroom> StudentClassrooms { get; set; }
        public virtual DbSet<StudentHistory> StudentHistories { get; set; }
        public virtual DbSet<StudentPersonal> StudentPersonals { get; set; }
        public virtual DbSet<StudentSchool> StudentSchools { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
    }
}
