//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPersonal
    {
        public int idStudent { get; set; }
        public int School_idSchool { get; set; }
        public string name { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<long> contact { get; set; }
        public string prevSchool { get; set; }
        public Nullable<bool> currentlyStudying { get; set; }
        public string nextSchool { get; set; }
    
        public virtual School School { get; set; }
        public virtual StudentClassroom StudentClassroom { get; set; }
        public virtual StudentHistory StudentHistory { get; set; }
        public virtual StudentSchool StudentSchool { get; set; }
    }
}
