//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSchool
    {
        public int StudentPersonal_idStudent { get; set; }
        public string month_2 { get; set; }
        public Nullable<int> reading_decoding { get; set; }
        public Nullable<int> reading_comprehension { get; set; }
        public Nullable<int> reading_rate_fluency { get; set; }
        public Nullable<int> spelling_accuracy { get; set; }
        public Nullable<int> mathematics_computation { get; set; }
        public Nullable<int> mathematics_concepts { get; set; }
        public Nullable<int> handwriting { get; set; }
        public Nullable<int> writing_rate { get; set; }
        public Nullable<int> punctuation_grammer { get; set; }
        public Nullable<int> ability_to_express_thoughts_through_writing { get; set; }
        public Nullable<int> gross_motor_skills { get; set; }
        public Nullable<int> fine_motor_skills { get; set; }
    
        public virtual StudentPersonal StudentPersonal { get; set; }
    }
}
