//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentHistory
    {
        public int StudentPersonal_idStudent { get; set; }
        public int Teacher_idTeacher { get; set; }
        public Nullable<int> trouble_learning_new_material { get; set; }
        public Nullable<int> little_desire_to_master_new_skills { get; set; }
        public Nullable<int> unable_to_tell_time { get; set; }
        public Nullable<int> cannot_repeat_info { get; set; }
        public Nullable<int> trouble_multithinking { get; set; }
        public Nullable<int> trouble_following_multistep_directions { get; set; }
        public Nullable<int> difficulty_copying { get; set; }
        public Nullable<int> difficulty_orienting_self { get; set; }
        public Nullable<int> poor_spatial_judgement { get; set; }
        public Nullable<int> confuses_directions { get; set; }
        public Nullable<int> mixes_up_lower_and_upper_cases { get; set; }
        public Nullable<int> reverses_letters_and_numbers { get; set; }
        public Nullable<int> trouble_ordering_words_and_events { get; set; }
        public Nullable<int> mispronounciation { get; set; }
        public Nullable<int> trouble_verbally_expressing_thoughts { get; set; }
        public Nullable<int> little_to_no_connection_to_what_others_are_discussing { get; set; }
    
        public virtual StudentPersonal StudentPersonal { get; set; }
    }
}
