//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDevFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int idTeacher { get; set; }
        public int School_idSchool { get; set; }
        public string name { get; set; }
        public string subject { get; set; }
        public Nullable<long> contact { get; set; }
        public Nullable<long> salary { get; set; }
    
        public virtual School School { get; set; }
    }
}
